"""Glossaire FR→EN du domaine (repli hors ligne si le modèle neuronal est absent)
et corrections appliquées après la traduction neuronale."""

# Expressions (plusieurs mots) : traitées en premier, les plus longues d'abord.
FR_EN = {
    # --- expressions
    "apprentissage automatique": "machine learning",
    "apprentissage profond": "deep learning",
    "apprentissage supervisé": "supervised learning",
    "apprentissage non supervisé": "unsupervised learning",
    "apprentissage par renforcement": "reinforcement learning",
    "intelligence artificielle": "artificial intelligence",
    "réseau de neurones": "neural network",
    "réseaux de neurones": "neural networks",
    "traitement du langage naturel": "natural language processing",
    "traitement automatique des langues": "natural language processing",
    "vision par ordinateur": "computer vision",
    "recherche d'information": "information retrieval",
    "recherche d'informations": "information retrieval",
    "système de recherche": "retrieval system",
    "fouille de textes": "text mining",
    "fouille de données": "data mining",
    "exploration de données": "data mining",
    "science des données": "data science",
    "base de données": "database",
    "bases de données": "databases",
    "lac de données": "data lake",
    "données massives": "big data",
    "internet des objets": "internet of things",
    "objets connectés": "connected objects",
    "réseau de capteurs": "sensor network",
    "réseaux de capteurs sans fil": "wireless sensor networks",
    "réseau sans fil": "wireless network",
    "point d'échange internet": "internet exchange point",
    "points d'échange internet": "internet exchange points",
    "fournisseur d'accès": "internet service provider",
    "système autonome": "autonomous system",
    "systèmes autonomes": "autonomous systems",
    "détection d'intrusion": "intrusion detection",
    "détection d'intrusions": "intrusion detection",
    "détection d'anomalies": "anomaly detection",
    "déni de service": "denial of service",
    "sécurité informatique": "computer security",
    "sécurité des réseaux": "network security",
    "cybersécurité": "cybersecurity",
    "logiciel malveillant": "malware",
    "logiciels malveillants": "malware",
    "chiffrement": "encryption",
    "cryptographie à courbes elliptiques": "elliptic curve cryptography",
    "courbe elliptique": "elliptic curve",
    "informatique en nuage": "cloud computing",
    "nuage informatique": "cloud computing",
    "réseau sur puce": "network on chip",
    "programmation linéaire en nombres entiers": "integer linear programming",
    "transformée de hough": "hough transform",
    "traitement d'images": "image processing",
    "reconnaissance d'images": "image recognition",
    "recherche d'images": "image retrieval",
    "drone": "unmanned aerial vehicle",
    "caméra thermique": "thermal camera",
    "engin explosif": "explosive device",
    "système tutoriel intelligent": "intelligent tutoring system",
    "système d'information": "information system",
    "systèmes d'information": "information systems",
    "système d'information hospitalier": "hospital information system",
    "dossier médical": "medical record",
    "services web": "web services",
    "web sémantique": "semantic web",
    "wiki sémantique": "semantic wiki",
    "savoirs endogènes": "endogenous knowledge",
    "savoir endogène": "endogenous knowledge",
    "changement climatique": "climate change",
    "consommation d'énergie": "energy consumption",
    "consommation électrique": "electricity consumption",
    "énergie solaire": "solar energy",
    "réseau électrique": "power grid",
    "série temporelle": "time series",
    "séries temporelles": "time series",
    "forêt aléatoire": "random forest",
    "arbre de décision": "decision tree",
    "machine à vecteurs de support": "support vector machine",
    "classification de textes": "text classification",
    "analyse de sentiments": "sentiment analysis",
    "géolocalisation": "geolocation",
    "réseaux sociaux": "social networks",
    "réseau social": "social network",
    "langue locale": "local language",
    "langues locales": "local languages",
    "commerce électronique": "e-commerce",
    "gouvernement électronique": "e-government",
    "administration électronique": "e-government",
    "santé publique": "public health",
    "aide à la décision": "decision support",
    "villes intelligentes": "smart cities",
    "agriculture de précision": "precision agriculture",
    "télédétection": "remote sensing",
    "image satellite": "satellite image",
    "images satellites": "satellite images",
    "comptage d'arbres": "tree counting",
    "noix de cajou": "cashew",
    "anacardier": "cashew tree",
    "bétail": "cattle",
    "bovins": "cattle",
    "coton": "cotton",
    "paludisme": "malaria",
    "schistosomiase": "schistosomiasis",
    "qualité de l'eau": "water quality",
    # --- mots simples
    "détection": "detection", "détecter": "detect", "intrusion": "intrusion", "intrusions": "intrusions",
    "réseau": "network", "réseaux": "networks", "sécurité": "security", "attaque": "attack",
    "attaques": "attacks", "menace": "threat", "menaces": "threats", "vulnérabilité": "vulnerability",
    "vulnérabilités": "vulnerabilities", "trafic": "traffic", "chiffré": "encrypted",
    "authentification": "authentication", "clé": "key", "clés": "keys", "capteur": "sensor",
    "capteurs": "sensors", "routage": "routing", "topologie": "topology", "mesure": "measurement",
    "mesures": "measurements", "internet": "internet", "afrique": "africa", "africain": "african",
    "africains": "african", "burkina": "burkina", "apprentissage": "learning",
    "classification": "classification", "prédiction": "prediction", "prévision": "forecasting",
    "modèle": "model", "modèles": "models", "algorithme": "algorithm", "algorithmes": "algorithms",
    "données": "data", "donnée": "data", "jeu": "set", "ensemble": "set", "texte": "text",
    "textes": "texts", "document": "document", "documents": "documents", "requête": "query",
    "requêtes": "queries", "recherche": "search", "indexation": "indexing", "index": "index",
    "ontologie": "ontology", "ontologies": "ontologies", "connaissance": "knowledge",
    "connaissances": "knowledge", "sémantique": "semantic", "agriculture": "agriculture",
    "agricole": "agricultural", "agricoles": "agricultural", "agriculteur": "farmer",
    "agriculteurs": "farmers", "climat": "climate", "santé": "health", "médical": "medical",
    "médicale": "medical", "hôpital": "hospital", "maladie": "disease", "maladies": "diseases",
    "diagnostic": "diagnosis", "patient": "patient", "patients": "patients", "éducation": "education",
    "enseignement": "teaching", "étudiant": "student", "étudiants": "students", "université": "university",
    "universités": "universities", "orientation": "guidance", "tutoriel": "tutoring",
    "langue": "language", "langues": "languages", "mooré": "moore", "mot": "word", "mots": "words",
    "image": "image", "images": "images", "vidéo": "video", "arbre": "tree", "arbres": "trees",
    "comptage": "counting", "détection d'objets": "object detection", "objet": "object",
    "objets": "objects", "énergie": "energy", "électricité": "electricity", "consommation": "consumption",
    "ville": "city", "villes": "cities", "gouvernement": "government", "gouvernemental": "government",
    "site": "website", "sites": "websites", "entreprise": "company", "entreprises": "companies",
    "cloud": "cloud", "nuage": "cloud", "puce": "chip", "tweet": "tweet", "tweets": "tweets",
    "covid": "covid", "pandémie": "pandemic", "épidémie": "epidemic", "eau": "water",
    "optimisation": "optimization", "simulation": "simulation", "performance": "performance",
    "évaluation": "evaluation", "analyse": "analysis", "architecture": "architecture",
    "plateforme": "platform", "système": "system", "systèmes": "systems", "application": "application",
    "applications": "applications", "mobile": "mobile", "téléphonie": "telephony",
    "télécommunications": "telecommunications", "satellite": "satellite", "logiciel": "software",
    "matériel": "hardware", "intelligent": "intelligent", "intelligente": "intelligent",
    "automatique": "automatic", "neuronal": "neural", "neuronaux": "neural", "profond": "deep",
    "supervisé": "supervised", "similarité": "similarity", "cosinus": "cosine", "vecteur": "vector",
    "vecteurs": "vectors", "plongement": "embedding", "plongements": "embeddings",
    "traduction": "translation", "information": "information", "informations": "information",
    "fiabilité": "reliability", "confidentialité": "privacy", "protection": "protection",
    "surveillance": "surveillance", "alerte": "alert", "carte": "map", "cartographie": "mapping",
    "élevage": "livestock", "culture": "crop", "cultures": "crops", "récolte": "harvest",
    "sol": "soil", "explosif": "explosive", "explosifs": "explosives", "enfoui": "buried",
    "enfouis": "buried", "thermique": "thermal",
}

# Corrections des contresens fréquents du modèle neuronal sur le vocabulaire du domaine
EN_FIXES = {
    "automatic learning": "machine learning",
    "automated learning": "machine learning",
    "deep training": "deep learning",
    "exchange points internet": "internet exchange points",
    "detection of intrusion": "intrusion detection",
    "detection of intrusions": "intrusion detection",
    "detection of anomalies": "anomaly detection",
    "networks of sensors": "sensor networks",
    "search for information": "information retrieval",
    "natural language treatment": "natural language processing",
    "learning by strengthening": "reinforcement learning",
}

# Mots-outils français ignorés par la traduction par glossaire
FR_FUNCTION_WORDS = {
    "le", "la", "les", "un", "une", "des", "du", "de", "d", "l", "et", "ou", "en", "dans", "pour",
    "par", "sur", "avec", "au", "aux", "à", "ce", "ces", "cette", "qui", "que", "qu", "son", "sa",
    "ses", "leur", "leurs", "est", "sont", "comment", "quels", "quelles", "quel", "quelle", "entre",
}
